apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front50
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front50
    spec:
      containers:
      - name: front50
        image: quay.io/spinnaker/front50
        command:
        - "/bin/bash -c 'sleep 5; /opt/front50/bin/front50'"
        ports:
        - containerPort: 8080