apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-front50secret
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-front50secret
    spec:
      volumes:
      - name: spinnaker-config
        secret:
          secretName: spinnaker-config
      containers:
      - name: spin-front50secret
        volumeMounts:
        - mountPath: /opt/front50/config
          name: spinnaker-config
        image: quay.io/spinnaker/front50
        ports:
        - containerPort: 8080