apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-front50
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-front50
    spec:
      containers:
      - name: spin-front50
        image: quay.io/spinnaker/front50
        ports:
        - containerPort: 8080