apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: work
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - name: work
        image: quay.io/spinnaker/front50
        ports:
        - containerPort: 8080
        command:
        - "/bin/sh"
        - "-c"
        - "sleep 5; /opt/front50/bin/front50"