aws:
  enabled: false
azure:
  enabled: false
cf:
  accounts:
  enabled: false
credentials:
  challengeDestructiveActionsEnvironments: default
  primaryAccountTypes: default
default:
  account:
    env: default
dockerRegistry:
  accounts:
  - address: https://index.docker.io
    name: dockerhub
    repositories:
    - library/nginx
  enabled: true
google:
  enabled: false
kubernetes:
  accounts:
  - dockerRegistries:
    - accountName: dockerhub
    name: minikube
  enabled: true
redis:
  connection: redis://spin-redis:6379
server:
  port: 7002
services:
  front50:
    baseUrl: http://spin-front50:8080
udf:
  enabled: false
