apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-deck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-deck
    spec:
      volumes:
      - name: nginx-config
        secret:
          secretName: nginx-config
      volumes:
      - name: deck-build
        emptyDir: {}
      containers:
      - name: deck-build
        volumeMounts:
        - mountPath: /deckbuild
          name: deck-build
        volumeMounts:
        - mountPath: /nginxconfig
          name: nginx-config
        image: quay.io/spinnaker/deck
        env:
        - name: CI
          value: "true"
        - name: API_HOST
          value: /gate
        - name: BAKERY_DETAIL_URL
          value: /bakery
        command:
          - "/bin/sh"
          - "-c"
          - "npm install; npm run build; mv build/webpack /deckbuild/deck; apt-get install -y nginx"
        ports:
        - containerPort: 80
