apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-jenkins
    spec:
      containers:
      - name: spin-jenkins
        securityContext:
          privileged: true
        image: chadmoon/jenkins-dind
        ports:
        - containerPort: 8080
        command:
          - "bash"
          - "-c"
          - "nohup dockerd-entrypoint.sh & sleep 5; java -jar /usr/local/jenkins/jenkins.war"