apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spin-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spin-registry
    spec:
      containers:
      - name: spin-registry
        image: registry:2.4.1
        ports:
        - containerPort: 5000
      - name: spin-registryui
        image: hyper/docker-registry-web
        ports:
        - containerPort: 8080
        env:
        - name: REGISTRY_URL
          value: http://spin-registry:5000/v2
        env:
        - name: REGISTRY_NAME
          value: spin-registry